### ISSUE TITLE
Q: API: 403 The request signature we calculated does not match the signature you provided

### ISSUE THREAD

**Issue by roosi** [aws/aws-amplify#69]
I created API through awsmobile could-api and it looks like this

```
      hello: !com.amazonaws.mobilehub.v0.API 
        attributes:
          name: hello
          requires-signin: true
        paths:
          /hello: !com.amazonaws.mobilehub.v0.Function 
            name: hello
            codeFilename: uploads/hello-20171214123204.zip
            handler: lambda.handler
            enableCORS: true
            runtime: nodejs6.10
            environment: {}
          '/hello/{proxy+}': !com.amazonaws.mobilehub.v0.Function 
            name: hello
            codeFilename: uploads/hello-20171214123204.zip
            handler: lambda.handler
            enableCORS: true
            runtime: nodejs6.10
            environment: {}
```

When I call it without query parameters `API.get('hello', '/hello')` it works fine, but if I add anything to query e.g. `API.get('hello', '/hello?name=John')` I will get following error

403
{"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."}

Is my configuration wrong or what I am doing wrong?

**Comment by ephopper** [comment]
I'm using aws-amplify-react-native and was running into this issue as well. After digging around for a bit, it appears to be coming from the [canonical_request function in Signer.js](https://github.com/aws/aws-amplify/blob/4cc30296d3af3180c1f3d2d426e03e9551c91afa/packages/aws-amplify-react-native/src/Common/Signer.js#L86). (in aws-amplify, it appears to be the same in [Signer.ts](https://github.com/aws/aws-amplify/blob/4cc30296d3af3180c1f3d2d426e03e9551c91afa/packages/aws-amplify/src/Common/Signer.ts#L87))
the return statement shows:
`return [request.method || '/', url_info.path,` .....
however this should be `url_info.pathname` instead of `url_info.path`
`url_info.path` includes the query string along with the path, whereas` url_info.pathname` is simply the path by itself.
Also, if your query string has more than one parameter it will throw the same 403 error due to the parameters not being sorted per the signature version 4 specs.
When I sort the parameters and modify the return statement appropriately, my calls are successful
```
var sorted_query = url_info.query.split('&').sort((a,b) => a < b ? -1 : 1).join('&');
return [request.method || '/', url_info.pathname, sorted_query, canonical_headers(request.headers), signed_headers(request.headers), hash(request.data)].join('\n');
```

**Comment by roosi** [comment]
Any updates on this? This makes API unusable.

**Comment by mlabieniec** [comment]
@roosi @ephopper when you pass query string parameters, you need to pass them as part of the `init` argument object with the `queryStringParameters` object on the API request. This is because the rest api setup with the cli is a lambda proxy integration:

    let items = await API.get('sampleCloudApi', '/items', {
      'queryStringParameters': {
        'test': '1'
      }
    });

You can then access them within Lambda on the `event["queryStringParameters"]['...']`

**Comment by twoolf** [comment]
I'm wondering if anyone working on the aws-amplify code-base has suggestions on this for the aws-mobile-react-native-starter (petfinder).  Right now, at least on multiple builds with different variations of the aws-amplify, different JDK versions (most recently: jdk1.8.0_151.jdk, but have tried others), and variations within the package.json, I continue to have 403-errors with an API.get that is using the format in the docs (e.g.: return await API.post(apiName, path, myInit); )  -- I'm happy to add more and/or to try other combinations of versions if there are suggestions.

**Comment by manueliglesias** [comment]
@twoolf The react native starter has included some changes in awslabs/aws-mobile-react-native-starter#39, in particular to fix the signing process (See #128 and #129)

Please try with the latest versions of both the starter and the aws-amplify-react-native packages and let us know how it goes.

**Comment by justhamade** [comment]
@mlabieniec looks like #127 says this is not supported yet

**Comment by chapeljuice** [comment]
Added the work around suggested by @ephopper 
https://github.com/aws/aws-amplify/pull/190

**Comment by richardzcode** [comment]
released the fix

**Comment by causingchaos2** [comment]
I believe i'm having issues with this topic as well..  How do you access queryStringParameter, if I remove the extra JSON argument in the call to API.get it works perfect! I'm just trying to figure out if this is indeed a problem with AWS amplify and how i'm sending the JSON parameter.

My client side code (aws-amplify 0.2.11 ):
`return API.get('trips','/days', {'queryStringParameters': {'param1': "99b60260-363c-11e8-b7ca-250a890d0675"}}) `

My API side code ( using serverless-webpack v 1.6.0, aws sdk v 2.202.0 ) :
serverless.yml file : 
```
listDays:
        handler: listDays.main
        events:
          - http:
              path: days
              method: get
              cors: true
              authorizer: aws_iam

```
API-javascript code trying to access the event:
```
export async function main(event,context,callback) {

    const params = {
        TableName: "DAYS",

        KeyConditionExpression: "tripId = :tripId",
        ExpressionAttributeValues: {
            ":tripId": event.queryStringParameters.param1
        }
    }

  //console.log(data.tripId)
    try {
        //result will return an array of trips
        const result = await dynamoDbLib.call("query", params)
        callback(null, success(result.Items))
    } catch (e) {
        callback(null, failure({status: false}))
    }
}

```
