### ISSUE TITLE
Cognito - Login page redirected to error page with limited details

### ISSUE THREAD

**Issue by tarundhillon** [aws/aws-amplify#755]
Do you want to request a feature or report a bug? Bug

What is the current behavior?
I have been using "amazon-cognito-identity-js": "^2.0.3" for few months and starting 27 April'18, the application has stopped working across all instances 

I am using token based login, url below 

> https://xxxxx.auth.eu-west-2.amazoncognito.com/oauth2/authorize?response_type=code&client_id=xxxxxxxxxxxx&redirect_uri=http://xxxxxxxxxxx/auth/callback&scope=email+openid+profile+aws.cognito.signin.user.admin&state=STATE

The above url re-directs to 

> https://xxxxx.auth.eu-west-2.amazoncognito.com/error#

The re-directed pages shows the below error and the link "View error" doesn't provide any details
> An error was encountered with the requested page. View error

What is the expected behavior?
The link should be redirected to Cognito login page. 

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

"amazon-cognito-identity-js": "^2.0.3"

I have been re-directed to aws-amplify from https://github.com/aws/amazon-cognito-identity-js, from the notes on the repository, I believe the github location has been changed but no regression impact has been highlighted.

**Comment by yuntuowang** [comment]
Hi @tarundhillon, now the /oauth2/authorize hosted UI urls work as expected. Thanks!

**Comment by tarundhillon** [comment]
Thanks I can confirm it works now. 

Wondering what was the root cause ? Also was this limited only to a certain user section, as I think authorize flow would quite an important flow for a lot for users.

**Comment by cnkhandar** [comment]
Hi there,

I am facing same issue as of today. I have selected OAuth 2.0 option in App Client Settings as suggested. But still same error.

**Comment by mrichman** [comment]
Same issue here. I get the ambiguous error "An error was encountered with the requested page"

**Comment by csdal** [comment]
Same issue: An error was encountered with the requested page.

**Comment by jhw** [comment]
@mrichman - did you manage to resolve this ?

**Comment by csdal** [comment]
@mrichman @jhw 
How about this?
https://github.com/csdal/public-junk/issues/2

**Comment by mrichman** [comment]
@jhw I don't recall my specific issue, but to open the Cognito hosted UI from within Vue.js, I just call `Auth.federatedSignIn();` on button click. My `aws-exports.js` is configured as follows:

```
const config = {
  Auth: {
    region: 'us-east-1',
    identityPoolId: 'us-east-1:696b4ac4-dead-beef-cafe-31e83abec5a7',
    userPoolId: 'us-east-1_pxxxxxkIjj',
    userPoolWebClientId: '5gha7s6xxxxxxxpe5i9resj',
    oauth: {
      domain: 'xxxxxxxxxx.auth.us-east-1.amazoncognito.com',
      scope: ['email', 'profile', 'openid'],
      redirectSignIn: 'http://localhost:8080/',
      redirectSignOut: 'http://localhost:8080/',
      responseType: 'code',
      mandatorySignIn: true,
    },
  },
  Storage: {
    AWSS3: {
      bucket: 'xxxxxxxx',
      region: 'us-east-1',
    },
  },
  Analytics: {
    disabled: false,
    autoSessionRecord: true,
    AWSPinpoint: {
      appId: process.env.PINPOINT_APP_ID,
      region: 'us-east-1',
    },
  },
};

export default config;

```

**Comment by jhw** [comment]
@mrichman many thanks. Wondering if you have any Cloudformation at hand for creating a user pool + app client + hosted UI ? Am working from this base -

https://gist.github.com/singledigit/2c4d7232fa96d9e98a3de89cf6ebe7a5

but the UserPoolClient defined there is extremely simple and doesn't seem to include the Hosted UI stuff. Reading around a bit I find that Cloudformation Cognito UI support was only added in the ast year -

https://aws.amazon.com/about-aws/whats-new/2019/10/amazon-cognito-increases-cloudformation-support/

and in particular these new fields for AWS::Cognito::UserPoolClient

https://stackoverflow.com/a/58285550/124179

Now trying to figure out how to map those  new fields to console- based configuration of App Client shown here -

https://itnext.io/aws-cognito-example-using-react-ui-and-node-js-rest-apis-part-1-cognito-setup-5597acb02db4

Wondering if you might have a short cut readily available :-) (no worries if not, just wondering)

**Comment by mrichman** [comment]
Try these:

```yaml
UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: yournamehere-UserPool
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: true

UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: yournamehere-UserPoolClient
      GenerateSecret: false # set to false for web clients
      PreventUserExistenceErrors: ENABLED
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_CUSTOM_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs: !Ref ClientDomains
      LogoutURLs: !Ref ClientDomains
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
```

**Comment by jhw** [comment]
@mrichman thank you so much. 

Now this compiles (== no Cloudformation errors) but weird thing is I can't find the hosted UI endpoint. I was expecting it to be at -

`https://#{my_user_pool_client_name}.auth.#{my_region}.amazoncognito.com`

but `This site can’t be reached` :(

Could I missing a attribute to expose the hosted UI endpoint somehow ? Full stack here -

https://gist.githubusercontent.com/jhw/e4f06a3b0f9a50239db9855a80194651/raw/df093c697ea3634ecac538fb4e781208ebce0813/stack.yaml

(not expecting you to do free work for me. But do need to get this fixed. So happy to contact u privately if need be. Many thanks)

**Comment by mrichman** [comment]
@jhw Try creating a user pool domain:

```yaml
UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    UpdateReplacePolicy: Delete
    Properties:
      Domain: <the thing before ".auth" in the hosted UI hostname>
      UserPoolId: !Ref UserPool
```

See here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpooldomain.html
